### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [bobcao3/svg-rasterizer#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114332582-17f1c200-9b79-11eb-8430-b3d01cdf6426.png)
  

![image](https://user-images.githubusercontent.com/51076736/114332610-2049fd00-9b79-11eb-9d75-d55bd75188cc.png)

thank you  
best regards to you  
William

**Comment by bobcao3** [comment]
Hi,

It seems the ImGUI in this repo is old, probably nothing I can do. The
project is not updating
